baseURL = 'https://stotrasamhita.github.io/'
locale = 'en'
title = 'Stotra Samhita'
theme = 'hugo-book'
disablePathToLower = true
enableGitInfo = true

[markup.goldmark.renderer]
  unsafe = true

[params]
  BookSection = '*'
  BookSearch = true
  BookComments = false
  BookLogo = 'logo.png'

[taxonomies]
  deity = 'deities'
  composer = 'composers'
  chandas = 'meters'
